#!/bin/sh
# File generated by ocamlbuild

cd /home/vigand/Documents/4A/Prog_Fonctionnelle/Projet-OCAML/src

rm -f graph.cmi
rm -f graph.cmo
# Also clean the script itself
rm -f /home/vigand/Documents/4A/Prog_Fonctionnelle/Projet-OCAML/src/_build/sanitize.sh
